"""
Component operations tool handlers for enhanced component placement, deletion, and manipulation
"""
import json
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from mcp.server.fastmcp import FastMCP
    from ..altium_bridge import AltiumBridge


def register_component_ops_tools(mcp: "FastMCP", altium_bridge: "AltiumBridge"):
    """Register all component operation tools"""

    @mcp.tool()
    async def place_component(
        designator: str,
        footprint: str,
        x: float,
        y: float,
        layer: int = 0,
        rotation: int = 0
    ) -> str:
        """
        Place a single component on the PCB board with specified footprint and position

        This is the fixed version of component placement that properly handles footprint library
        lookup and component creation. It searches through all loaded libraries to find the
        specified footprint and creates a fully functional component on the board.

        Args:
            designator: Component reference designator (e.g., "R1", "C5", "U3")
            footprint: Name of the footprint from library (e.g., "0805", "SOIC-8", "QFN-24")
            x: X coordinate in millimeters
            y: Y coordinate in millimeters
            layer: Layer to place on - 0 for top layer, 1 for bottom layer (default: 0)
            rotation: Rotation angle in degrees, 0-360 (default: 0)

        Returns:
            JSON object with success status and component details

        Example:
            place_component("R1", "0805", 10.0, 20.0, 0, 90)
        """
        response = await altium_bridge.call_script("place_component", {
            "designator": designator,
            "footprint": footprint,
            "x": x,
            "y": y,
            "layer": layer,
            "rotation": rotation
        })

        if not response.success:
            return json.dumps({
                "success": False,
                "error": f"Failed to place component: {response.error}"
            })

        return json.dumps(response.data, indent=2)

    @mcp.tool()
    async def delete_component(designator: str) -> str:
        """
        Delete a component from the PCB board by its designator

        Args:
            designator: Component reference designator to delete (e.g., "R1", "C5", "U3")

        Returns:
            JSON object with success status and message

        Example:
            delete_component("R1")
        """
        response = await altium_bridge.call_script("delete_component", {
            "designator": designator
        })

        if not response.success:
            return json.dumps({
                "success": False,
                "error": f"Failed to delete component: {response.error}"
            })

        return json.dumps(response.data, indent=2)

    @mcp.tool()
    async def place_component_array(
        footprint: str,
        ref_des: str,
        start_x: float,
        start_y: float,
        spacing_x: float,
        spacing_y: float,
        rows: int,
        cols: int
    ) -> str:
        """
        Place an array of components in a grid pattern with automatic designator assignment

        This tool is useful for placing multiple identical components (like resistors, capacitors,
        or LEDs) in a regular grid pattern. Designators are automatically generated by appending
        sequential numbers to the reference designator prefix.

        Args:
            footprint: Name of the footprint from library (e.g., "0805", "LED-0603")
            ref_des: Reference designator prefix (e.g., "R", "C", "LED")
            start_x: Starting X coordinate in millimeters
            start_y: Starting Y coordinate in millimeters
            spacing_x: Horizontal spacing between components in millimeters
            spacing_y: Vertical spacing between components in millimeters
            rows: Number of rows in the array
            cols: Number of columns in the array

        Returns:
            JSON object with success status, count, and list of placed component designators

        Example:
            place_component_array("0805", "R", 10.0, 10.0, 5.0, 5.0, 2, 3)
            # Places R1, R2, R3, R4, R5, R6 in a 2x3 grid
        """
        response = await altium_bridge.call_script("place_component_array", {
            "footprint": footprint,
            "ref_des": ref_des,
            "start_x": start_x,
            "start_y": start_y,
            "spacing_x": spacing_x,
            "spacing_y": spacing_y,
            "rows": rows,
            "cols": cols
        })

        if not response.success:
            return json.dumps({
                "success": False,
                "error": f"Failed to place component array: {response.error}"
            })

        return json.dumps(response.data, indent=2)

    @mcp.tool()
    async def align_components(
        designators: str,
        alignment: str
    ) -> str:
        """
        Align multiple components to a common edge

        This tool aligns the specified components by moving them so they share the same
        X or Y coordinate based on the alignment type. Useful for organizing components
        in neat rows or columns.

        Args:
            designators: Comma-separated list of component designators (e.g., "R1,R2,R3,C1")
            alignment: Type of alignment - "left", "right", "top", or "bottom"
                      - "left": Align to leftmost component's X coordinate
                      - "right": Align to rightmost component's X coordinate
                      - "top": Align to topmost component's Y coordinate
                      - "bottom": Align to bottommost component's Y coordinate

        Returns:
            JSON object with success status, alignment type, and count of aligned components

        Example:
            align_components("R1,R2,R3", "left")
            # Aligns R1, R2, and R3 to the leftmost component's X position
        """
        response = await altium_bridge.call_script("align_components", {
            "designators": designators,
            "alignment": alignment.lower()
        })

        if not response.success:
            return json.dumps({
                "success": False,
                "error": f"Failed to align components: {response.error}"
            })

        return json.dumps(response.data, indent=2)
